name: dsp_rs
description: 'Native bindings to dsp.rs'
version: 0.0.1
homepage: 'https://github.com/Piero512/dsp_rs.dart'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.piero512.dsp_rs
        pluginClass: DspRsPlugin
      ios:
        pluginClass: DspRsPlugin
      linux:
        pluginClass: DspRsPlugin
      macos:
        pluginClass: DspRsPlugin
      windows:
        pluginClass: DspRsPlugin
ffigen:
  output: 'lib/src/dsp_rs.dart'
  headers:
    entry-points:
      - 'dsp_rs.h'
    include-directives:
      - '**dsp_rs.h'
  name: 'DspRs'
  description: 'Native bindings to dsp.rs'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names'